name: Terraform Deploy
on:
  push:
    branches:
      - github-actions
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: dev
        required: false
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug
        run: ls -al
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false 
        working-directory: ./terraform
        


# test
